### ISSUE TITLE
Cannot use CSS modules with bundle option

### ISSUE THREAD

**Issue by Blond11516** [parcel-bundler/parcel-css#102]
It appears there is an incompatibility between the `--bundle` and `--css-modules` options. When bundling files together, the CSS modules option only generates a single modules file (the `.json` file containing the mapping between the source and generated indentifiers). This causes issues when trying to use the same class name in multiple modules, as only one of the generated class names will be present in the mappings, making all other generated class names effectively unusable.

Here is a repo reproducing the issue: https://github.com/Blond11516/parcel-css-bundle-modules-repro

<details><summary>Here are the example css files and generated module file for quick reference</summary><p>

```css
/* index.css */

@import "app.css";

.test {
	color: red;
}
```

```css
/* app.css */

.test {
	color: blue;
}
```

```jsonc
// bundle.json

{"test":{"name":"test_C-gzXq","composes":[],"isReferenced":false}}
```
</p></details>

The issue would be fixed by generating a different module file for every CSS file. If the fix is deemed to hard to implement or undesirable by the maintainers I think emitting a warning at runtime when both options are detected, or at least mentioning this in the docs, would be appreciated.

I know very little about Rust but if the fix is simple enough that a beginner could implement it with some guidance I'd be happy to try and give it a go!

**Comment by arthurdenner** [comment]
What would be the expected outcome in this case?
Ideally, a JSON file shouldn't contain two keys with the same value.

* Should the bundle output be an array instead of key-value and have a new `filename` property?
  * Currently: `Record<string, { name, composes, isReferenced }>`)
  * After: `Record<string, { name, composes, isReferenced, filename }>[]`
* Should the value change to be an array instead of an object?
  * Currently: `Record<string, { name, composes, isReferenced }>`)
  * After: `Record<string, { name, composes, isReferenced }[]>`

**Comment by Blond11516** [comment]
Using arrays is interesting but it would be a departure from the traditional format generated by the likes of [postcss-modules](https://github.com/madyankin/postcss-modules).

postcss-modules is probably the most popular tool when it comes to CSS modules, so even though it's by no means official, I think it would be fair to consider it the current standard and try to stick to it. I expect most existing tooling to have an implicit dependency on this output format, so doing something different would hinder the adoption of parcel-css as a CSS modules processor in my opinion.

With that said, I think the only way to match postcss-modules' output format would be to generate a different JSON file for every input CSS file. So if I have the following input structure:
- index.css
- subfolder_a/
  - a.css
- subfolder_b/
  - b.css

The output would have to look like this:
- bundle.css
- index.json
- subfolder_a/
  - a.json
- subfolder_b/
  - b.json

Given that this probably represents more work than changing the output file format, I'll try to do some more research on the modules ecosystem to validate my assumptions.

**Comment by devongovett** [comment]
Actually, I think what should happen is that both CSS classes get renamed to the _same_ name. That's how we handle it in Parcel (the bundler) today. `postcss-modules` doesn't handle `@import` rules by itself. You'd have to combine it with `postcss-import`, which would inline the two files together before `postcss-modules` gets to it. Then, both classes would end up with the same name.

**Comment by Blond11516** [comment]
Doesn't that defeat the purpose of CSS modules? If both classes are going to be renamed to the same thing I might just use global CSS, no?

**Comment by devongovett** [comment]
Both classes will end up on the same element in either case, so isn't it the same thing?

**Comment by Blond11516** [comment]
Why would they end up on the same element? For me the main advantage of CSS modules is that I can reuse class names in multiple places without risking collisions. I can't do that if all usages of a class name get renamed to the same thing.

Here's an example to make sure we have the same thing in mind.

Say I have two components: a button and a textbox. I want them both to support either a `primary` or a `secondary` style. With CSS modules, I expect to be able to turn
```css
/* button.css */

.primary { background-color: blue; }
.secondary { background-color: red; }

/* textbox.css */

.primary { color: blue; }
.secondary { color: red; }
```

into
```css
/* bundle.css */

.button_primary { background-color: blue; }
.button_secondary { background-color: red; }
.textbox_primary { color: blue; }
.textbox_secondary { color: red; }
```

If I understand correctly you're suggesting that the output should look something like this (both classes renamed to the same name then, I assume, still bundled together)?
```css
/* bundle.css */

.primary_some_hash { background-color: blue; }
.secondary_some_hash { background-color: red; }
.primary_some_hash { color: blue; }
.secondary_some_hash { color: red; }
```
