### ISSUE TITLE
Property sorting can break border-image

### ISSUE THREAD

**Issue by jakelazaroff** [parcel-bundler/parcel-css#103]
When `@parcel/css` sorts properties, it places `border-image-source` before `border`. The `border` shorthand sets `border-style` (if not given explicitly, it defaults to `currentColor`) which overrides the border image and prevents it from showing up.

```css
/* input css */
.test {
  border: 10px solid;
  border-image-source: url(image.png);
}

/* after @parcel/css sorts it */
.test {
  border-image-source: url(image.png);
  border: 10px solid;
}
```

Here's a [JSFiddle displaying the behavior](https://jsfiddle.net/bLuvaj0s/2/) (comment out the second `border: 30px solid;` to see the image).

You can work around this by explicitly setting `border-width` and `border-style`, which get sorted after `border-image-source`, but it took me a while to figure out what was wrong.
