### ISSUE TITLE
[Feature Request] Add support for merging @media and @supports queries.

### ISSUE THREAD

**Issue by SukkaW** [parcel-bundler/parcel-css#104]
E.g.:

```css
@media screen and (min-width: 480px) {
  .a { color: red }
}

@media screen and (min-width: 480px) {
  .b { color: blue }
}

@media (min-width: 480px) {
  .c { color: green }
}

@media (max-width: 769px) {
  .d { color: yellow }
}

@media screen and (min-width: 480px) {
  .e { color: orange }
}
```

Should become:

```css
@media screen and (min-width: 480px) {
  /* This two can be safely merged */
  .a { color: red }
  .b { color: blue }
}

/* Non identical @media query shouldn't be merged */
@media (min-width: 480px) {
  .c { color: green }
}

@media (max-width: 769px) {
  .d { color: yellow }
}

/* Although it is an identical media query as before, but it shouldn't be merged into .a & .b  */
@media screen and (min-width: 480px) {
  .e { color: orange }
}
```
