### ISSUE TITLE
Color-mix function with CSS variables

### ISSUE THREAD

**Issue by LuukLeijtens** [parcel-bundler/parcel-css#112]
I'm trying to use CSS variables in the color-mix function but this doesn't seem to work or is this not supported yet?

```css
.foo {
  --brand: #0088e3;
  background: color-mix(in lch, var(--brand) 65%, black);
}
```

[Example](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20--brand%3A%20%230088e3%3B%5Cn%20%20background%3A%20color-mix(in%20lch%2C%20var(--brand)%2065%25%2C%20black)%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%7D)
