### ISSUE TITLE
Correct handling of `<family-name>` in font-family

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/parcel-css#120]
## Input

```css
.foo {
  font-family: 'sans-serif', 'default';
}
```

## Output

```css
.foo {
  font-family: sans-serif, default;
}
```

![image](https://user-images.githubusercontent.com/2784308/159428125-c04f92f4-27e3-4298-967e-b4676e9ff11c.png)

## Expected

```css
.foo {
  font-family: 'sans-serif', 'default';
}
```

`font-family: sans-serif` means that a generic `sans-serif` font family will be used, while `font-family: 'sans-serif'` (with quotes) refers to an actual font that goes by the name of `sans-serif`.

## [CSS Spec](https://www.w3.org/TR/css-fonts-4/#example-c2604b3d)
> Note: this means that if you really have a font whose name is the same as one of the [<generic-family>](https://www.w3.org/TR/css-fonts-4/#generic-family-value)[](https://www.w3.org/TR/css-fonts-4/#example-c2604b3d) names, or the common-keywords|CSS-wide keyword values, it must be quoted.

> To illustrate this, the following unusual font family names are valid because they are quoted:
font-family: "sans-serif", sans-serif;
font-family: "default", sans-serif;
font-family: "initial", sans-serif;
font-family: "inherit", sans-serif;

The full CSS-wide keyword(common-keywords) and `<generic-family>` in the current specification include:

### CSS-wide keyword

https://www.w3.org/TR/css-values-4/#common-keywords

```
"initial"
"inherit"
"unset"
```

### `<generic-family>`

https://www.w3.org/TR/css-fonts-4/#generic-font-families

```
"serif"
"sans-serif"
"cursive"
"fantasy"
"monospace"
"system-ui"
"emoji"
"math"
"fangsong"
"ui-serif"
"ui-sans-serif"
"ui-monospace"
"ui-rounded"
```

Here's a lint tool: https://mothereff.in/font-family

**Comment by yisibl** [comment]
There are more case test failures:

https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#valid_family_names

## Input
```css
.foo {
  font-family: "Goudy Bookletter 1911", sans-serif;
  font-family: "Red/Black", sans-serif;
  font-family: "test@foo", sans-serif;
  font-family: "#POUND", sans-serif;
  font-family: "Hawaii 5-0", sans-serif;  
}
```

## Output

```css
.foo{font-family:"Hawaii 5-0",sans-serif}
```
