### ISSUE TITLE
grid-template parsing error

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/parcel-css#123]
MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template

## Input

```css
.foo {
    grid-template: 'img   content'     auto    / auto   1fr;
}

.bar {
    grid: 'img   content'   auto /    auto   1fr;
}

.baz {
  grid-template: 'img'    auto     'content'     auto   /  100%;
}
```

## Output

```css
.foo{grid-template:"img content"/auto 1fr}
.bar{grid:"img content"/auto 1fr}
.baz{grid-template:"img""content"/100%}
```

## Expected

```css
.foo{grid-template:"img content"auto/auto 1fr}
.bar{grid:"img content"auto/auto 1fr}
.baz{grid-template:"img"auto"content"auto/100%}
```
