### ISSUE TITLE
CSS minify got the incorrect output when rotate has specific values.

### ISSUE THREAD

**Issue by jinliming2** [parcel-bundler/parcel-css#127]
For example:
https://parcel-css.vercel.app/#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22%40keyframes%20antRotate%20%7B%5Cn%20%20from%20%7B%5Cn%20%20%20%20transform%3A%20rotate(45deg)%3B%5Cn%20%20%7D%5Cn%20%20to%20%7B%5Cn%20%20%20%20transform%3A%20rotate(405deg)%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%7D

```css
@keyframes antRotate {
  from {
    transform: rotate(45deg);
  }
  to {
    transform: rotate(405deg);
  }
}
```

Expected: The rotate value kept as is.

Actual: The target rotate value becomes `45deg`.

The rotate value should be kept as is, otherwise, the animation won't work.
