### ISSUE TITLE
`border`, `border-*`, and `outline` shorthand leaves extra space when omitting `color`

### ISSUE THREAD

**Issue by nevanscott** [parcel-bundler/parcel-css#130]
Given input like:

```css
.foo {
  border: solid 1px;
}
```

Gives output like:

```css
.foo {
  border: 1px solid ;
}
```

Note the extra space.

The minified version also retains the space:

```css
.foo{border:1px solid }
```

I think expected output should be:

```css
.foo {
  border: 1px solid;
}
```

In other words, without the space.

The same happens with:

- `border-top`
- `border-right`
- `border-bottom`
- `border-left`
- `border-block`
- `border-inline`
- `border-block-start`
- `border-block-end`
- `border-inline-start`
- `border-inline-end`
- `outline`

It also leaves the space when supplying the keyword `currentColor`.
