### ISSUE TITLE
CSS modules option changes grid template area names

### ISSUE THREAD

**Issue by cedeber** [parcel-bundler/parcel-css#144]
Hello, 

If you just try:
```css
.test {
    grid-area: page-header;
}
```

on the Playground it will result to:
```css
.test_EgL3uq {
  grid-area: page-header_EgL3uq;
}
```

As you can see the area name is rewritten and will have the current module uid as suffix.
This is unfortunate as another module could place an element in the grid-template area defined in another CSS module.
So, in the end, the names won't be the same and it will simply break the app layout.

Just image you have a PageLayout component which defines a grid-template and other components like NavigationPanel, Header, Content that will define in which area of the grid they will be rendered.

In my opinion, grid-template area names shouldn't be rewritten at all.

Thanks.

PS: I can help with Rust if you can give me a hint where to look at ;-)

**Comment by devongovett** [comment]
CSS module hashing affects anything that uses the `<custom-ident>` syntax. That includes `@keyframes`, `@counter-style`, etc. as well.

A common way around this is to create a class within the file that defines the grid template, and either access it directly from your JS, or use the `composes` property within another CSS file.


```css
/* page.css */
.page {
  grid-template-areas: 
    "header header"
    "nav main";
}

.header {
  grid-area: header;
}

/* header.css */
.header {
  composes: header from './page.css';
  /* other header styles */
}
```
