### ISSUE TITLE
Pseudo selector throws Invalid state

### ISSUE THREAD

**Issue by waltonseymour** [parcel-bundler/parcel-css#149]
The following css from blueprint throws an exception in 1.8.0:
```css
.bp3-file-input input:disabled + .bp3-file-upload-input::after.bp3-active,
.bp3-file-input input:disabled + .bp3-file-upload-input::after.bp3-active:hover,
.bp3-file-input input.bp3-disabled + .bp3-file-upload-input::after.bp3-active,
.bp3-file-input
  input.bp3-disabled
  + .bp3-file-upload-input::after.bp3-active:hover {
  background: rgba(206, 217, 224, 0.7);
}
```

```
@parcel/transformer-css: Invalid state
```

This css did not throw any errors with @parcel/transformer-sass 2.1.1
