### ISSUE TITLE
Support @container

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/parcel-css#158]
- [Safari Technology Preview 142](https://webkit.org/blog/12522/release-notes-for-safari-technology-preview-142/) has container queries [enabled](https://trac.webkit.org/changeset/290025/webkit/). 
- https://caniuse.com/css-container-queries
- Spec https://drafts.csswg.org/css-contain-3/

## Input

```css
@supports ( container-type: size ) {
  @container ( width <= 150px ) {
    #inner {
      background-color: skyblue;
    }
  }
}
```

## Output

```css
@supports(container-type:size){@container(width<=150px){#inner{background-color:#87ceeb}}}
```

**Comment by yisibl** [comment]
Syntax update:
- Disallow and/not/or from <container-name> https://chromium-review.googlesource.com/c/chromium/src/+/3698402

**Comment by yisibl** [comment]
I tested it and found some minor problems:

## Should throw an error
```css
@container not ( width >= 100px ) {
  .foo {
    color: red;
  }
}
```

## The range syntax should not be converted

### Input
```css
@container not ( width >= 100px ) {
  .foo {
    color: red;
  }
}
```

### Expected
```css
@container not ( width >= 100px ) {
  .foo {
    color: red;
  }
}
```

I have added more tests in the PR https://github.com/parcel-bundler/parcel-css/pull/223
