### ISSUE TITLE
Segmentation Fault on complicated `calc`/`clamp` expression

### ISSUE THREAD

**Issue by danieldiekmeier** [parcel-bundler/parcel-css#166]
Hello! 

I just tried to minify our (pretty legacy) CSS with Parcel CSS to see if I could squeeze out a few bytes. Sadly, I encountered a Segmentation Fault. I bisected our CSS file until I arrived at this gnarly expression (simplified for easier consumption):

```css
.foo {
  left: calc(50% - 100px + clamp(0px, calc(50vw - 50px), 100px));
}
```

This script reproduces the error:

```js
// index.js
const css = require('@parcel/css')

css.transform({
  filename: 'style.css',
  code: Buffer.from(
    '.foo {left: calc(50% - 100px + clamp(0px, calc(50vw - 50px), 100px));}'
  )
})
```

Executed via:

```
$ node index.js
[1]    22519 segmentation fault  node index.js
```

The error is pretty specific: If I reorder the parts, it often starts to work. For example:

```css
.foo {
  left: calc(50% + clamp(0px, calc(50vw - 50px), 100px) - 100px);
}
```

As a workaround, because we're only exploring Parcel CSS, I manually reordered the one case in our large CSS file where this problem occured. But maybe you're still interested in solving this issue? Thanks in advance!

## Versions:

Node: v16.4.2
OS: macOS 12.3.1, ARM 64
Parcel CSS: 1.8.1
