### ISSUE TITLE
z-index rounded

### ISSUE THREAD

**Issue by damusnet** [parcel-bundler/parcel-css#170]
Any z-index value above `999999` seems to get rounded:

[<img width="1552" alt="image" src="https://user-images.githubusercontent.com/433409/166395485-8824873f-0f5a-400e-b8af-e2207b518168.png">](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A5963776%7D%2C%22source%22%3A%22%20%20%20%20.foo%20%7B%20z-index%3A%202147483647%20%7D%5Cn%20%20%20%20.bar%20%7B%20z-index%3A%201147483647%20%7D%5Cn%20%20%20%20.baz%20%7B%20z-index%3A%20147483647%20%7D%5Cn%20%20%20%20.lor%20%7B%20z-index%3A%201000002%20%7D%5Cn%20%20%20%20.ips%20%7B%20z-index%3A%201000001%20%7D%5Cn%20%20%20%20.dol%20%7B%20z-index%3A%201000000%20%7D%5Cn%20%20%20%20.sit%20%7B%20z-index%3A%20999999%20%7D%5Cn%20%20%20%20.ame%20%7B%20z-index%3A%20999998%20%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

Despite 2147483647 being the seemingly [most common answer](https://stackoverflow.com/a/491105/233404) for max z-index value:

> most browsers limit it to signed 32-bit values (−2147483648 to +2147483647) in practice

**Comment by yisibl** [comment]
Similar problems exist with `<integer>` values in other properties.

## input

```css
.foo {
    aspect-ratio: 99999988888;
    column-count: 99999988888;
    counter-increment: my-counter 99999988888;
}
```

## Output

```css
.foo {
  aspect-ratio: 100000000000;
  column-count: 100000000000;
  counter-increment: my-counter 100000000000;
}
```
