### ISSUE TITLE
comma-less colors not downleveled with CSS variable

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel-css#178]
Input:
```css
.text-white {
   --tw-text-opacity: 1;
   color: rgb(255 255 255 / var(--tw-text-opacity));
}

.red {
   color: rgb(255 255 255 / 0.5);
}
```

Output with Chrome 54 as target:
```css
.text-white {
  --tw-text-opacity: 1;
  color: rgb(255 255 255 / var(--tw-text-opacity) );
}

.red {
  color: rgba(255, 255, 255, .5);
}
```

https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A3538944%7D%2C%22source%22%3A%22.text-white%20%7B%5Cn%20%20%20--tw-text-opacity%3A%201%3B%5Cn%20%20%20color%3A%20rgb(255%20255%20255%20%2F%20var(--tw-text-opacity))%3B%5Cn%7D%5Cn%5Cn.red%20%7B%5Cn%20%20%20color%3A%20rgb(255%20255%20255%20%2F%200.5)%3B%5Cn%7D%5Cn%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D

**Comment by devongovett** [comment]
hmm this will be hard as variables can expand to multiple tokens, e.g.

```css
.test {
  --test: 255 / .5;
  color: rgb(255 255 var(--test));
}
```

because of this, we don't currently parse values with variables at all, and just pass through the raw tokens.

**Comment by mischnic** [comment]
But for the case I posted, you can assume that the variable expands to just a number, right? Otherwise it would be invalid in the original syntax as well.

Looks like there's no crosslinking between discussions, so this is where I found this: https://github.com/parcel-bundler/parcel/discussions/8092 (Tailwind). So this will be a very common case.

**Comment by devongovett** [comment]
in the case where only one component is a variable it might work, yes. otherwise, we'd have to somehow also convert the variable value too.

**Comment by devongovett** [comment]
The problem is `rgb(0 0 var(--test))` is ambiguous. If we inserted commas there, it might be broken if the variable expanded to include multiple tokens. But that is also valid if the variable only expanded to a single number, in which case adding the commas would be right. So we could really only do this in this one exact case where we have 3 values and the slash, and not every case with space separated values. PostCSS seems to make some unsafe assumptions here and always adds the commas regardless of how many parameters you have.

**Comment by romainmenke** [comment]
> PostCSS seems to make some unsafe assumptions here and always adds the commas regardless of how many parameters you have.

Can you specify which plugin is doing this?
Just ran a test in `postcss-color-functional-notation` and got this :

```css
.test-var {
	color: rgb(var(--r) 0 0 / 1);
	color: rgb(0 var(--g) 0 / 1);
	color: rgb(0 0 var(--b) / 1);
	color: rgb(0 0 0 / var(--a));
}

.test-calc {
	color: rgb(calc(1 + 1) 0 0 / 1);
	color: rgb(0 calc(1 + 1) 0 / 1);
	color: rgb(0 0 calc(1 + 1) / 1);
	color: rgb(0 0 0 / calc(1 + 1));
}
```

becomes :

```css
.test-var {
	color: rgb(var(--r) 0 0 / 1);
	color: rgb(0 var(--g) 0 / 1);
	color: rgb(0 0 var(--b) / 1);
	color: rgba(0, 0, 0, var(--a));
}

.test-calc {
	color: rgb(calc(1 + 1) 0 0 / 1);
	color: rgb(0 calc(1 + 1) 0 / 1);
	color: rgb(0 0 calc(1 + 1) / 1);
	color: rgba(0, 0, 0, calc(1 + 1));
}
```

If we do have a bug somewhere in a csstools package I am happy to fix this :)
