### ISSUE TITLE
Support width: fill-available/stretch

### ISSUE THREAD

**Issue by LB4027221** [parcel-bundler/parcel-css#186]
for example: 
width: fill-available;    should transfer to   width: -webkit-fill-available; width: -moz-fill-available;

**Comment by yisibl** [comment]
Current browser implementations are `-webkit-fill-available` or `-moz-available`, and while this is not consistent with the `stretch` name in the [CSS spec](https://www.w3.org/TR/css-sizing-4/#valdef-width-stretch), given that it is already widely supported, we should support automatically prefixing them, which is also consistent with Autoprefixer. 

The main point is that there are many pages that already actually use `width: fill-available`, which can break the user experience of migrating to parcel-css.

## Autoprefixer

### input

```css
.foo {
  width: fill-available;
}

.bar {
  width: stretch;
}
```

### output

```css
/*
* Prefixed by https://autoprefixer.github.io
* PostCSS: v8.4.12,
* Autoprefixer: v10.4.4
* Browsers: > 0%
*/

.foo {
  width: -webkit-fill-available;
  width: -moz-available;
  width: fill-available;
}

.bar {
  width: -webkit-fill-available;
  width: -moz-available;
  width: stretch;
}
```
