### ISSUE TITLE
BlueprintJS CSS: Invalid state due to awkward mix of pseudo elements and classes

### ISSUE THREAD

**Issue by alexeyraspopov** [parcel-bundler/parcel-css#189]
As I was trying to make something with Parcel (v2.4.1) in my project, it occurred that blueprintjs as a dependency keeps failing the build, due to CSS parser saying following piece of code is "invalid state" (primarily pointing to `::after.bp3-active` part. Being honest, it's the first time I look at this code and I agree with Parcel CSS that this combination is awful. But it seems to be a valid CSS regardless.

```css
.bp3-file-input input:disabled + .bp3-file-upload-input::after.bp3-active, .bp3-file-input input:disabled + .bp3-file-upload-input::after.bp3-active:hover,
        .bp3-file-input input.bp3-disabled + .bp3-file-upload-input::after.bp3-active,
        .bp3-file-input input.bp3-disabled + .bp3-file-upload-input::after.bp3-active:hover{
          background:rgba(206, 217, 224, 0.7); }
```

"Invalid state" is reproducible in https://parcel-css.vercel.app/.
