### ISSUE TITLE
Conversion error when `calc()` is included in `@media`

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/parcel-css#195]
## Input

```css
@media (width > calc(1px + 1rem)) {
  body { background-color: green; }
}
```

## output

```css
@media (min-width: calc(1px + 1rem) + .001px) {
  body {
    background-color: green;
  }
}
```

`@media (min-width: calc(1px + 1rem) + .001px)` is an invalid CSS syntax.
