### ISSUE TITLE
better error tolerance of wrong css rule

### ISSUE THREAD

**Issue by hardfist** [parcel-bundler/parcel-css#209]
I seems parcel-css will throw all the rule following unsupport rule
```css
h1(>h1) {
  color: red;
}

div {
  color: blue;
}

```
![image](https://user-images.githubusercontent.com/8898718/174285106-180d1555-1abc-48c6-9fa7-4dadec4428f8.png)

the correct rule
```css
div {
 color: blue
}
```
should be preserved but is discarded by parcel-css

and maybe the wrong rule should be preserved even it's recognized by compiler( which may be recognized by future browser for new css feature)
```css
h1(>h1){
  color: red;
}
```
