### ISSUE TITLE
Don't always convert `dppx` unit to `x` unit in resolution media queries

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/parcel-css#229]
[css-values-4](https://github.com/w3c/csswg-drafts/issues/2631) adds `x` as an alias for `dppx` unit, but not every browser in media queries supports `x` unit. So I think it would be better to add a fallback for `x` unit.

`x` unit support in: `Chrome 68+, Edge 79+, Opera 55+, Safari 16+, Firefox 62+`

## Input

```css
@media (resolution: 1dppx) { /* or resolution: 1x */
    body {
       background: red;
    }
}
```

## Output

```css
@media (resolution: 1x) {
    body {
       background: red;
    }
}
```
## Expected

```css
@media (resolution: 1dppx), (resolution: 1x) {
    body {
       background: red;
    }
}
```

## Minify

When compressing, if the configured browser version does not support `x` unit, only `dppx` will be retained.

```css
@media (resolution: 1dppx) {
    body {
       background: red;
    }
}
```

See also: https://github.com/postcss/autoprefixer/pull/1468
