### ISSUE TITLE
Downlevel logical properties

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel-css#23]
https://caniuse.com/css-logical-props

Only supported very recently. It can be down leveled, but might need to be opt-in because this changes the specificity of rules and requires a `dir` attribute to be placed on an ancestor element (since `:dir(...)` is not yet widely supported (https://caniuse.com/css-dir-pseudo).

```css
.foo {
  margin-inline-start: 10px;
}
```

to

```css
[dir="ltr"] .foo {
  margin-left: 10px;
}

[dir="rtl"] .foo {
  margin-right: 10px;
}
```

See https://github.com/csstools/postcss-logical and https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-dir-pseudo-class
