### ISSUE TITLE
Minifier for `@font-face` strips whitespace between `url()` and `format()`

### ISSUE THREAD

**Issue by rng-al** [parcel-bundler/parcel-css#236]
Hi,

The minifier for `@font-face` introduced in [this commit](https://github.com/parcel-bundler/parcel-css/commit/4d80479052b032e6390bf75a05ecf5b3dd2e6f9e) strips whitespace from between `url()` and `format()` in the `src` descriptor, potentially in contravention of the CSS spec.[^1][^2]

The spec seems a little open to interpretation on this point, and I'd personally be inclined to interpret it as you have (that no whitespace is required), but there are examples where stripping this whitespace causes failures in production.[^3]

For this reason it may be safest to put a single space between `url()` and `format()` when minifying.

## Example

CSS source:

```css
@font-face {
  font-family: 'My Font';
  src: url("/path/to/my_font.woff2") format("woff2");
}
```

Current behaviour minifies to:

```css
@font-face{font-family:'My Font';src:url("/path/to/my_font.woff2")format("woff2")}
```

Suggested behaviour (add a single space between `url()` and `format()`):

```css
@font-face{font-family:'My Font';src:url("/path/to/my_font.woff2") format("woff2")}
```

[^1]: [https://drafts.csswg.org/css-fonts/#font-face-src-parsing](https://drafts.csswg.org/css-fonts/#font-face-src-parsing)
[^2]: [https://drafts.csswg.org/css-values-4/#component-whitespace](https://drafts.csswg.org/css-values-4/#component-whitespace)
[^3]: The problem I have run into is that Stripe.js requires at least one space between `url()` and `format()` for [custom fonts loaded from a stylesheet](https://stripe.com/docs/js/appendix/css_font_source_object?type=paymentElement#css_font_source_object-cssSrc). I contacted their engineering team about this and they have little/no intention of changing this on their end because they interpret the CSS spec as requiring the whitespace. They told me I'll need to switch to another minifier and sent me [this online minifier](https://www.toptal.com/developers/cssminifier) as an example of one which 'correctly' preserves the whitespace. 🤷
