### ISSUE TITLE
Already prefixed mask-image results in two prefixed declarations

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel-css#237]
```css
.foo {
  -webkit-mask-image: url("x.svg");
  mask-image: url("x.svg");
}
```

results in 
```css
.foo {
  -webkit-mask-image: url("x.svg");
  -webkit-mask-image: url("x.svg");
  mask-image: url("x.svg");
}
```

Not sure if this is an isolated problem with mask-image or if this applies to other features as well.

https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6291456%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20-webkit-mask-image%3A%20url(%5C%22x.svg%5C%22)%3B%5Cn%20%20mask-image%3A%20url(%5C%22x.svg%5C%22)%3B%5Cn%7D%5Cn%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D
