### ISSUE TITLE
CSS modules: composes not mixing in code

### ISSUE THREAD

**Issue by joelmoss** [parcel-bundler/parcel-css#243]
I'm pretty sure I've got this right, but if I understand it correctly, this input:

```css
.classOne {
  font-size: 30px;
}

.classTwo {
  composes: classOne;
  color: red;
}
```

should result in this output...

```css
.abc123_classTwo {
  font-size: 30px;
  color: red;
}
```

however, when calling the CLI `bin/parcel_css test/internal/lib/foo.css --css-modules`, the output is:

```css
.B4x5qW_classOne {
  font-size: 30px;
}
.B4x5qW_classTwo {
  color: red;
}
```

Which is exactly the same output when `composes` is not used at all 🤷‍♂️
