### ISSUE TITLE
Remove duplicate declarations

### ISSUE THREAD

**Issue by tanishqkancharla** [parcel-bundler/parcel-css#245]
https://parcel-css.vercel.app/#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%5Cncolor%3A%20red%3B%5Cncolor%3A%20blue%3B%5Cnbackground-color%3A%20blue%3B%5Cnbackground-image%3A%20linear-gradient(to%20right%2C%20white)%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D

```css
.foo {
  color: red;
  color: blue;
  background-color: blue;
  background-image: linear-gradient(to right, white);
}
```

transforms into 

```css
.foo{color:red;color:#00f;background-color:#00f;background-image:linear-gradient(90deg,#fff)}
```

the first `color` declaration can be removed (especially when using minify)
