### ISSUE TITLE
Convert "individual transforms" to browser supported syntax

### ISSUE THREAD

**Issue by nicksrandall** [parcel-bundler/parcel-css#247]
Spec: https://drafts.csswg.org/css-transforms-2/#individual-transforms

Basically convert:
```css
.target {
  translate: 50% 0;
  rotate: 30deg;
  scale: 1.2;
}
```

to

```css
.target {
  transform: translateX(50%) rotate(30deg) scale(1.2);
}
```

Helpful article: https://web.dev/css-individual-transform-properties/

**Comment by devongovett** [comment]
It already happens (since https://github.com/parcel-bundler/parcel-css/commit/cc54e46f3e1c775cbe42b43e60828a49baeb8b78), but you must define the `transform` property as well, e.g.

```css
.foo {
  transform: none;
  rotate: 10deg;
  translate: 10px;
}
```

[Example](https://parcel-css.vercel.app/#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A3276800%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20transform%3A%20none%3B%5Cn%20%20rotate%3A%2010deg%3B%5Cn%20%20translate%3A%2010px%3B%5Cn%7D%5Cn%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

This is because the `transform` property may be defined in a different rule for the same element, and `transform` combines with individual transform properties. For example:

```css
.a {
  transform: translate(10px);
}

.b {
  transform: 10px;
}
```

In this example, an element like `<div class="a b">` would be translated by `20px`, not `10px`. If we converted individual transforms to the `transform` property, it would override the other rule instead of combining.
