### ISSUE TITLE
Fallback background-image is overwritten when using image-set

### ISSUE THREAD

**Issue by maxnordlund** [parcel-bundler/parcel-css#252]
When using a [`background-image: image-set(...)`](https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set()) the recommendation is to have a fallback `background-image: url(...)`, however that fallback is currently removed by `parcel-css`.

This is broken out from https://github.com/parcel-bundler/parcel-css/issues/109#issuecomment-1112120278

Expected:
```css
.example {
    background-image: url("background.png");
    background-image: image-set(
        url("background.avif") type("image/avif"),
        url("background.png") type("image/png")
    );
}
```

To become:
```css
.example {
    background-image: url("background.png");
    background-image: -webkit-image-set(
        url("background.avif") type("image/avif"),
        url("background.png") type("image/png")
    );
    background-image: image-set(
        url("background.avif") type("image/avif"),
        url("background.png") type("image/png")
    );
}
```

But became:
```css
.example {
    /* Notice the missing background-image: url here */
    background-image: -webkit-image-set(
        url("background.avif") type("image/avif"),
        url("background.png") type("image/png")
    );
    background-image: image-set(
        url("background.avif") type("image/avif"),
        url("background.png") type("image/png")
    );
}
```

---

If you look at https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-image-set-function you can take this a step further by generating `@media` queries to try to emulate the switching for now supportive browsers as well.
