### ISSUE TITLE
BUG: `grid-template` area names incorrectly modfified with CSS Modules

### ISSUE THREAD

**Issue by marvinhagemeister** [parcel-bundler/parcel-css#257]
Noticed in my codebase that any file which is a CSS Module and uses CSS grids leads to broken layout. Narrowed it down to the module prefix being applied to the template area names too. Interestingly this seems to only happen for the `grid-template` and `grid-template-areas` property and not the others.

input.css :
```css
.grid {
  grid-template: "foo bar";
}

.foo {
  grid-template-area: foo;
}

.bar {
  grid-template-area: bar;
}
```

Command: 
```sh
parcel-css input.css --css-modules
```

Actual:

```css
.mo-vrq_grid {
  grid-template: "mo-vrq_foo mo-vrq_bar"; /* <- these shouldn't be modified */
}

.mo-vrq_foo {
  grid-template-area: foo;
}

.mo-vrq_bar {
  grid-template-area: bar;
}
```

Expected:

```css
.mo-vrq_grid {
  grid-template: "foo bar";
}

.mo-vrq_foo {
  grid-template-area: foo;
}

.mo-vrq_bar {
  grid-template-area: bar;
}
```
