### ISSUE TITLE
Preserve unused `@custom-media`

### ISSUE THREAD

**Issue by Marabyte** [parcel-bundler/parcel-css#258]
Hiya!

I'm bundling a CSS file that includes shared custom properties and custom media. Something like this:

```css
/** media-queries.css **/
@custom-media --breakpoint-large (width >= 75em);
```

```css
/** variables.css **/
:root {
--color-blue: blue;
}
```

```css
/** main.css **/
@import './variables.css';
@import './media-queries.css';
```
I bundle all the files using: 
```
parcel-css ./src/main.css --custom-media --bundle --targets 'last 2 versions' -o ./dist/global.css"
```
And this is the output:
```css
/** global.css **/
:root {
--color-blue: blue;
}
```
I'm assuming because the `@custom-media` is not used in the `global.css` it is removed from the file.

Is there a way to preserve the `@custom-media` declaration?

If I don't use the `--targets` flag in the CLI I almost get what I need but unfortunately semicolons are removed from the declaration:

```css
/** global.css **/
:root {
--color-blue: blue;
}
@custom-media --breakpoint-large (width >= 75em)
```

Causing it to not be parsed at all.
