### ISSUE TITLE
minifier: image-set broken in latest Chrome and more

### ISSUE THREAD

**Issue by jahudka** [parcel-bundler/parcel-css#262]
Given the following input:

```css
body {
  background-image: image-set("../images/bg.webp" 1x, "../images/bg.webp" 2x);
}
```

Running `parcel-css --targets '>= 0.25%' in.css -o out.css` will produce the following:

```css
body {
  background-image: -webkit-image-set(url("../images/bg.webp"), url("../images/bg.webp") 2x);
  background-image: image-set("../images/bg.webp", "../images/bg.webp" 2x);
}
```

Notice that the `1x` resolution specifier is gone from both the prefixed and the unprefixed property value.

I'm now testing this on Mac OS Big Sur in Safari 14.1 (yes, this is perhaps too old) and in Chrome 104 (which, on the other hand, is the latest version) and it works in neither: both browsers seem to need the `1x` resolution specifier. In Safari adding it fixes both the prefixed version and the unprefixed version, while in Chrome it only fixes the prefixed version (which is to be expected, since Chrome doesn't yet support the unprefixed version at all). According to the draft specification the resolution specifier is optional, but I'd argue at least Chrome has a large enough market share to warrant keeping those three bytes in there.. ;-)
