### ISSUE TITLE
Merging adjacent rules with the *almost* the same declarations

### ISSUE THREAD

**Issue by heypiotr** [parcel-bundler/parcel-css#271]
README says:
> Merging adjacent rules with the same selectors or declarations when it is safe to do so.

This works as advertised:

```css
.foo {
    background-color: red;
}
.bar {
    background-color: red;
}

/* output */
.foo,.bar{background-color:red}
```

But I wonder, is there any reason not to merge **partially**-indentical rules?

```css
.foo {
    background-color: red;
    padding: 20px;
}
.bar {
    background-color: red;
    padding: 40px;
}

/* actual output */
.foo{background-color:red;padding:20px}.bar{background-color:red;padding:40px}

/* better output? */
.foo,.bar{background-color:red}.foo{padding:20px}.bar{padding:40px}

/* or maybe even: */
.foo,.bar{background-color:red;padding:20px}.bar{padding:40px}
```

Or am I wrong to think that as long as the rules are adjacent, this should be safe to do?

(The gains aren't big in this simplified example, but we have CSS with long adjacent rules that differ in only one or two declarations, and it quickly adds up.)

**Comment by devongovett** [comment]
Note that in some cases, depending on the selector length, this may actually make the output larger. For example:

```css
.somelongselectorname{background-color:red;padding:20px}.someotherlongselectorname{background-color:red;padding:40px}

.somelongselectorname,.someotherlongselectorname{background-color:red;padding:20px}.someotherlongselectorname{padding:40px}
```
