### ISSUE TITLE
Rule merging problematic with unsupported selectors/pseudoclasses

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel-css#3]
```css
.form-input:-moz-placeholder-shown {
  color: black;
}
.form-input:-ms-input-placeholder {
  color: black;
}
.form-input:placeholder-shown {
  color: black;
}
```

is merged into a single rule. But browsers ignore rules with invalid selectors, so the rule won't apply on any browser.

via https://github.com/evanw/esbuild/releases/tag/v0.13.14
