### ISSUE TITLE
[Optimization] Initial background

### ISSUE THREAD

**Issue by Semigradsky** [parcel-bundler/parcel-css#41]
Before:
```css
    .a {
        background: none
    }
    .b {
        background: none center
    }
    .c {
        background: url("test.png") transparent none repeat scroll
    }
```

After:
```css
.a{background:#0000}.b{background:50% 50%}.c{background:url("test.png") transparent none repeat scroll}
```

For `.a` we even have deoptimization (`none` vs `#0000`).

Possible optimised output (from `csso`):
```css
.a{background:0 0}.b{background:center}.c{background:url(test.png)}
```
