### ISSUE TITLE
[Optimization] Initial font

### ISSUE THREAD

**Issue by Semigradsky** [parcel-bundler/parcel-css#42]
Before:
```css
.a {
    font: normal normal 600 9px/normal Charcoal;
}
.b {
    font: normal normal 500 medium/normal Charcoal;
}
.c {
    font: normal normal 400 medium Charcoal;
}
.d {
    font: normal normal 500 medium/10px Charcoal;
}
.e {
    font: normal;
}
.f {
    font: bold;
}
.g {
    font: medium;
}
```

After:
```css
.a{font:normal normal 600 9px/normal Charcoal}.b{font:normal normal 500 medium/normal Charcoal}.c{font:400px medium Charcoal}.d{font:normal normal 500 medium/10px Charcoal}.e{font:normal}.f{font:bold}.g{font:medium}
```

Possible optimised output (from `csso`):
```css
.a{font:600 9px Charcoal}.b{font:500 Charcoal}.c{font:400 Charcoal}.d{font:500 medium/10px Charcoal}.e{font:normal}.f{font:700}.g{font:normal}
```
