### ISSUE TITLE
Skips unrecognized at rules

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/parcel-css#45]
Unrecognized at rules should be skipped.

```css
@-ms-viewport {
  width: device-width;
}
```

```shell
SyntaxError: Unknown at rule: @-ms-viewport
```

https://github.com/twbs/bootstrap/blob/3b558734382ce58b51e5fc676453bfd53bba9201/dist/css/bootstrap.css#L53-L55

**Comment by devongovett** [comment]
I don't think we should skip them because that might change the behavior of the stylesheet. In this case, we should probably support parsing `@viewport` rules.

**Comment by yisibl** [comment]
I mean, when you encounter an unknown at rule, don't throw an error and just compress the code inside the `{}`. Because we don't know when new at rules will be added to the CSS spec in the future.

Input: 
```css
@foo {
  .bar {
    display: flex;
  }
}
```

Output:

```css
@foo{.bar{display: flex;}}
```
