### ISSUE TITLE
Minifier: Drop Redundant Doubled Properties

### ISSUE THREAD

**Issue by karlhorky** [parcel-bundler/parcel-css#47]
Hi @devongovett ! 👋  First of all, thanks for all of your effort on this, really amazing for the community to have such a great tool!

I was looking for a feature of `@parcel/css` that would allow for removal of duplicate properties.

For example:

**Input**

```css
div {
  color: green;
  color: red;
}
```

**`@parcel/css` Output**

```css
div{color:green;color:red}
```

**Expected Output**

```css
div{color:red}
```

However, it could be a problem with my understanding of the CSS spec somehow, because I see that some duplicated properties do indeed get dropped:

**Input**

```css
div {
  background: green;
  background: red;
}
```

**`@parcel/css` Output**

```css
div{background:red}
```

**Comment by devongovett** [comment]
Yeah, some properties are specially handled. For example, the `background` property is a shorthand, so it gets special treatment. At the moment, other properties are just passed straight through. We could probably do something here, but not sure how often duplicate properties are found in real-world code.

**Comment by karlhorky** [comment]
Ok, understood, thanks for the answer.

If this is not something that has a high likelihood of being addressed, then feel free to close too.

**Comment by deckchairlabs** [comment]
Delcaring props twice is usually used for fallbacks to supported values, for instance if a browser doesn't support CSS variables. Would probably need to be driven by browserlists targets.

```css
.foo {
  color: red; /* fallback */
  color: var(--red);
}
```
