### ISSUE TITLE
Feature request: support custom media queries

### ISSUE THREAD

**Issue by yoshuawuyts** [parcel-bundler/parcel-css#49]
The [Media Queries level 5 working draft](https://www.w3.org/TR/mediaqueries-5/#custom-mq) supports "custom media queries". This is one of the features required to use [open-props](https://open-props.style/) in a Rust application, but would be useful overall. Prior art exists in the [PostCSS Custom Media](https://github.com/postcss/postcss-custom-media) plugin. It'd be great if `parcel-css` could support this too. Thanks!

## Example

__input__
```css
/* --modern targets modern devices that support color or hover */
@custom-media --modern (color), (hover);

@media (--modern) and (width > 1024px) {
  .a { color: green; }
}
```

__output__
```css
@media ((color) or (hover)) and (width > 1024px) {
  .a { color: green; }
}
```

## References
- [Open Props](https://open-props.style/)
- [Media Queries level 5 spec](https://www.w3.org/TR/mediaqueries-5/#custom-mq)
- [PostCSS Custom Media plugin](https://github.com/postcss/postcss-custom-media)

**Comment by devongovett** [comment]
Makes sense. Do you know what the state of that spec is? How close is it to being done, and/or how likely is the syntax to change at this point?

**Comment by yoshuawuyts** [comment]
Ohh, I wish I did! The fact that it's being used as prominently as it is in `open-props` (made by chrome devrel folks) has me feeling somewhat optimistic about how far along it is.

Maybe the actual transform in `parcel-css` could be exposed behind a feature flag (e.g. `unstable_custom_media`) until the spec is elevated beyond the "working draft" stage?

**Comment by devongovett** [comment]
Yeah. We have a `drafts` option in the API for this, which is where the option to enable nesting is. I think we could put this in there as well.

One other question I had from reading the spec is whether the `@custom-media` declaration needs to come before it is used, or if something like this is valid:

```css
@media (--modern) and (width > 1024px) {
  .a { color: green; }
}

@custom-media --modern (color), (hover);
```

If that's the case, we'll need a two pass system for transforming rather than doing it during parsing.

**Comment by yoshuawuyts** [comment]
> One other question I had from reading the spec is whether the `@custom-media` declaration needs to come before it is used, or if something like this is valid:

Afaict all test cases for the PostCSS plugin [define `@custom-media` before it's used](https://cs.github.com/postcss/postcss-custom-media?q=%40custom-media). I think we should follow that behavior for now, in part to be compatible with `postcss`, but also because allowing use-before-declare semantics is backwards compatible [^compat]. Which luckily is also the simpler variant to implement.

[^compat]:  If we allow it without the spec specifically stating this is allowed, we could run into compatibility issues with the actual browser implementations later on too.

**Comment by devongovett** [comment]
Makes sense. I filed an issue on the spec to get it clarified as well: https://github.com/w3c/csswg-drafts/issues/6956

**Comment by devongovett** [comment]
Looked into it. There are some complicated corner cases here. For example:

```css
@custom-media --color-print print and (color);
@custom-media --color-screen screen and (color);

@media (--color-print) or (--color-screen) {}
```

This would need to become two media queries since media types cannot be combined in a single query:

```css
@media print and (color), screen and (color) {}
```

And if an `and` were used instead, the queries would need to be nested:

```css
@custom-media --not-print not print and (color);
@custom-media --not-screen not screen and (color);

@media (--not-print) and (--not-screen) {}
```

to:

```css
@media not print and (color) {
  @media not screen and (color) {}
}
```

In the general case, rules within the media query may even need to be duplicated:

```css
@custom-media --not-print not print and (color);
@custom-media --not-screen not screen and (color);

@media ((script) or ((--not-print) and (--not-screen))) {
  .a {
    color: green;
  }
}
```

would need to become:

```css
@media (script) {
  .a {
    color: green;
  }
}

@media not print and (color) {
  @media not screen and (color) {
    .a {
      color: green;
    }
  }
}
```

This seems quite difficult to implement. The PostCSS plugin doesn't seem to do it correctly either. I might simply error on boolean logic with media types for now. Not sure how widely used that will be. The common case (e.g. open props) is to use media conditions rather than media types, which can be done with a simple substitution.
