### ISSUE TITLE
Minifier: Merging classes with the same name

### ISSUE THREAD

**Issue by Marabyte** [parcel-bundler/parcel-css#50]
I'm not sure if this is a bug or feature.

```css
/*Input*/
.a { font-size: large; }
#b { color: aqua; }
.a { padding: 0.5rem; }
```
```css
/*Output*/
.a{font-size:large}#b{color:#0ff}.a{padding:.5rem}
```

But if we have the same class adjacent to each other
```css
/*Input*/
#b { color: aqua; }
.a { font-size: large; }
.a { padding: 0.5rem; }
```
```css
/*Output*/
#b{color:#0ff}.a{padding:.5rem;font-size:large}
```

I would expect both inputs to produce the same output (the second one).

**Comment by devongovett** [comment]
In general, merging non-adjacent selectors is not safe due to specificity. For example:

```css
<div class="a b">hi</div>
<style>
.a { color: green; }
.b { color: aqua; }
.a { color: red; }
</style>
```

In this example, the div should have red text. But if the `.a` selectors were merged, it would be aqua.

In your specific example, it the id selector has a higher specificity than the class selectors, so it could potentially work. But tracking whether there are only higher specificity selectors between two matching selectors seems hard and likely not worth it.
