### ISSUE TITLE
Some logical properties are supported but `inset` is not

### ISSUE THREAD

**Issue by onigoetz** [parcel-bundler/parcel-css#51]
I was having a look at what postcss plugins can be replaced by `@parcel/css` 

Since the documentation mentions that logical properties are supported, I tried it and got an incomplete result:

Input: 
```css
.banner {
    color: #222222;
    inset: logical 0 5px 10px;
    padding-inline: 20px 40px;
    resize: block;
    transition: color 200ms;
  }
```

Output according to https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-logical

```css
.banner:dir(ltr) {
  padding-left: 20px;
  padding-right: 40px;
}
.banner:dir(rtl) {
  padding-right: 20px;
  padding-left: 40px;
}
.banner {
  color: #222222;
  top: 0;
  left: 5px;
  bottom: 10px;
  right: 5px;
  resize: vertical;
  transition: color 200ms;
}
```

Output of `@parcel/css`, with `edge 18` as target browser

```
.banner {
  color: #222;
  inset: logical 0 5px 10px;
  resize: block;
  padding-left: var(--ltr, 20px) var(--rtl, 40px);
  padding-right: var(--ltr, 40px) var(--rtl, 20px);
  transition: color .2s;
}

[dir="ltr"] {
  --ltr: initial;
  --rtl: ;
}

[dir="rtl"] {
  --ltr: ;
  --rtl: initial;
}
```

I do get the trick with custom properties but `inset` should be converted into `top` `left`, `bottom` and `right`

Here's a link to the proposal : https://drafts.csswg.org/css-logical/#propdef-inset

Usually I'd propose to make a PR but I currently have no knowledge in Rust, I'll learn but that might take time.
