### ISSUE TITLE
Different values for vendor-prefixed shorthand properties causes decomposition into individual properties

### ISSUE THREAD

**Issue by toothbrush7777777** [parcel-bundler/parcel-css#70]
```css
.foo {
  -webkit-transition: background 200ms;
  -moz-transition: background 200ms;
  transition: background 230ms;
}
```

is transformed into

```css
.foo {
  transition-property: background;
  -webkit-transition-duration: .2s;
  -moz-transition-duration: .2s;
  -webkit-transition-delay: 0s;
  -moz-transition-delay: 0s;
  -webkit-transition-timing-function: ease;
  -moz-transition-timing-function: ease;
  transition-duration: .23s;
  transition-delay: 0s;
  transition-timing-function: ease;
}
```

I would expect to keep the shorthand properties.

[CSS playground](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20-webkit-transition%3A%20background%20200ms%3B%5Cn%20%20-moz-transition%3A%20background%20200ms%3B%5Cn%20%20transition%3A%20background%20230ms%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%7D)

Please note that the vendor-prefixed properties being different is unlikely to be the author's intent in most cases and the tool could produce a warning.
