### ISSUE TITLE
Analyze Dependencies in Custom Properties

### ISSUE THREAD

**Issue by jamiebuilds** [parcel-bundler/parcel-css#81]
Given a custom property containing a `url()`, right now Parcel CSS does not return it when analyzing dependencies.

```css
:root {
  --hero-background: #000 url(hero-image.jpeg); /* no dependency reported */
}

.hero {
  background: var(--hero-background);
}
```
