### ISSUE TITLE
Support `@property` at-rule

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/parcel-css#85]
https://developer.mozilla.org/en-US/docs/Web/CSS/@property

```css
@property --property-name {
    syntax: '<color>';
    inherits: false;
    initial-value: #c0ffee;
}
```
