### ISSUE TITLE
Support :nth-col* selector

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/parcel-css#87]
https://www.w3.org/TR/selectors-4/#the-nth-col-pseudo

```css
:nth-col(odd) {
    width: 10px;
}

:nth-col(2n+1) {
    width: 20px;
}

:nth-last-col(odd) {
    width: 30px;
}

:nth-last-col(2n+1) {
    width: 40px;
}
```
