### ISSUE TITLE
minifier: remove duplicate `!important`

### ISSUE THREAD

**Issue by yisibl** [parcel-bundler/parcel-css#88]
```css
:root {
    --foo: red !important;
    --foo: red!important;
}

div {
    color: red!important;
    color: red !important;
    color: red !   important;
    color: red   !   important;
    color: red   !   IMPORTANT;
    color: red   !   iMpOrTaNt;
}
```
