### ISSUE TITLE
Inline `var` after bundle

### ISSUE THREAD

**Issue by oovm** [parcel-bundler/parcel-css#93]
When the stylesheet is bundled, all variable relationships have been determined, and the quantities referenced by `var` can be inlined.

## Example

- input:

```css
.text-slate-500 {
    --tw-text-opacity: 1;
    color: rgb(100 116 139/var(--tw-text-opacity));
}

.bg-white {
    --tw-bg-opacity: 1;
    background-color: rgb(255 255 255/var(--tw-bg-opacity));
}
```

- output:

```css
.text-slate-500 {
    color: #64748b;
}

.bg-white {
    background-color: #fff;
}
```

## Design

```rust
struct VariableInlineOptions {
    ///
    enable: bool,
    /// local or global
    global: bool,
    /// do not inline in following selectors
    ///
    /// eg: `[:root]`
    exclude_selector: Vec<String>,
    /// do not inline the following variable
    ///
    /// eg: [`--main-bg-color`]
    exclude_variable: Vec<String>,
}
```
