### ISSUE TITLE
Better error message when & is not used at the beginning of a selector

### ISSUE THREAD

**Issue by bschlenk** [parcel-bundler/parcel-css#97]
Hey, really excited about this! The build times are really impressive.

With `drafts: { nesting: true }`, this css

```css
.a {
  .b & {
    color: red;
  }
}
```

Results in the error `SyntaxError: A nesting selector (&) is required as a prefix of each selector in a nested style rule.`. I think it would be helpful to point out that this actually _is_ valid syntax as long as the line is prefixed with `@nest`, like this:

```css
.a {
  @nest .b & {
    color: red;
  }
}
```

It would save people coming from sass (where this works without `@nest`) a lot of digging.
