### ISSUE TITLE
Option to not remove the space before/after CSS variables

### ISSUE THREAD

**Issue by saadeghi** [parcel-bundler/parcel-css#98]
I want to minify this
```css
:root {
  font: var(--font-size) / var(--line-height) var(--font-family);
}
```
to this (see the spaces between variables)
```css
:root{font:var(--font-size) / var(--line-height) var(--font-family)}
```
but currently all spaces are being removed
```css
:root{font:var(--font-size)/var(--line-height)var(--font-family)}
```
[[example link](https://parcel-css.vercel.app/#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22%3Aroot%20%7B%5Cn%20%20font%3A%20var(--font-size)%20%2F%20var(--line-height)%20var(--font-family)%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%7D)]

**Why does it matter?**

Because there's [an issue from `postcss-values-parser`](https://github.com/postcss/postcss-custom-properties/issues/225) and the currently only workaround is to add spaces before and after the `/` which is between CSS variables.
If I minify my CSS using Parcel CSS and someone use `postcss-values-parser` on it, it will cause error.

I'm just wondering if there's a way to keep that space between variables.
